"""empty message

Revision ID: 39dcab9aac40
Revises: 7ba812d63ffa
Create Date: 2019-02-27 21:36:57.254850

"""
from alembic import op
import sqlalchemy as sa
from ecom.models import custom_datatypes


# revision identifiers, used by Alembic.
revision = '39dcab9aac40'
down_revision = '7ba812d63ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'active')
    # ### end Alembic commands ###
