"""empty message

Revision ID: 7ba812d63ffa
Revises: a712be9a9b26
Create Date: 2019-02-25 16:17:33.448578

"""
from alembic import op
import sqlalchemy as sa
from ecom.models import custom_datatypes


# revision identifiers, used by Alembic.
revision = '7ba812d63ffa'
down_revision = 'a712be9a9b26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
